SKIPMOUNT=false
PROPFILE=false
POSTFSDATA=false
LATESTARTSERVICE=false

print_modname() {
  ui_print "   *************************"
  ui_print "      MIUI DEBLOATER"
  ui_print "   *************************"
}

REPLACE="
/system/app/AnalyticsCore
/system/app/BookmarkProvider
/system/app/BuiltInPrintService
/system/app/Calculator
/system/app/CarrierDefaultApp
/system/app/Cit
/system/app/CloudService
/system/app/com.miui.qr
/system/app/EasterEgg
/system/app/facebook-appmanager
/system/app/FidoAuthen
/system/app/FidoClient
/system/app/FileExplorerGlobal
/system/app/GooglePrintRecommendationService
/system/app/Health
/system/app/WapiCertManage
/system/app/PrintSpooler
/system/app/ModemTextBox
/system/app/MiuiBluethoot
/system/app/com.miui.qr
/system/app/HybridAccessory
/system/app/HybridPlatform
/system/app/IdMipay
/system/app/InMipay
/system/app/Joyose
/system/app/Lens
/system/app/mi_connect_service
/system/app/MiCloudSync
/system/app/MiGalleryLockscreen
/system/app/MiLinkService2
/system/app/MiPicks
/system/app/MiPlayClient
/system/app/MiRadio
/system/app/MiuiBugReport
/system/app/MiuiCompass
/system/app/MiuiDaemon
/system/app/MiuiVideoPlayer
/system/app/MiuiScreenRecorder
/system/app/MSA-Global
/system/app/Netflix_activation
/system/app/Notes
/system/app/OsuLogin
/system/app/PartnerBookmarksProvider
/system/app/PaymentService
/system/app/PlayAutoInstallStubApp
/system/app/Stk
/system/app/TouchAssistant
/system/app/Traceur
/system/app/VsimCore
/system/app/wps_lite
/system/app/WAPPushManager
/system/app/XMSFKeeper
/system/app/XiaomiSimActivateService
/system/data/app/android.autoinstalls.config.Xiaomi.qssi-5NKLAXthPp3xU6ucgGl2Ag==
/system/data/app/com.google.android.ims-zFXerSRh5hdqjerjDEJGyQ==
/system/priv-app/Browser
/system/priv-app/Calendar
/system/priv-app/CleanMaster
/system/priv-app/CloudBackup
/system/priv-app/CloudServiceSysbase
/system/priv-app/GameCenterGlobal
/system/priv-app/GoogleTTS
/system/priv-app/GlobalMinusScreen
/system/priv-app/MiBrowserGlobal
/system/priv-app/MiCalendarGlobal
/system/priv-app/MiDrop
/system/priv-app/MiService
/system/priv-app/MiShare
/system/priv-app/MiuiBrowserGlobal
/system/priv-app/MiuiGallery
/system/priv-app/MiuiMusicGlobal
/system/priv-app/MiuiScanner
/system/priv-app/ONS
/system/priv-app/ProxyHandler
/system/priv-app/SoundRecorder
/system/priv-app/Stk1
/system/priv-app/Tag
/system/priv-app/UserDictionaryProvider
/system/priv-app/YellowPage
/system/priv-app/Weather
/system/priv-app/facebook-installer
/system/priv-app/facebook-services
/system/product/app/Chrome
/system/product/app/Gmail2
/system/product/app/GoogleOne
/system/product/app/Maps
/system/product/app/remoteSimLockAuthentication
/system/product/app/FM
/system/product/app/Cit
/system/product/app/wps-lite
/system/product/app/Updater
/system/product/app/TouchAssistant
/system/product/app/NextPay
/system/product/app/PaymentService
/system/product/app/Cit
/system/product/app/MiuiVideoGlobal
/system/product/app/MiuiCompass
/system/product/app/MiLinkService
/system/product/app/MiGameService
/system/product/app/MiGalleryLockscreen
/system/product/app/MiConnectService
/system/product/app/Joyose
/system/product/app/Notes
/system/product/app/Health
/system/product/app/com.xiaomi.macro
/system/product/app/Email
/system/product/app/Calculator
/system/product/app/GoogleTTS
/system/product/app/YouTube
/system/product/app/uimremoteclient
/system/product/app/uimremoteserver
/system/product/priv-app/AndroidAutoStub
/system/product/priv-app/HotwordEnrollmentOKGoogleCORTEXM4
/system/product/priv-app/HotwordEnrollmentXGoogleCORTEXM4
/system/product/priv-app/Wellbeing
/system/product/priv-app/Velvet
/system/product/priv-app/EmergencyInfo
/system/product/priv-app/GoogleAssistant
/system/product/priv-app/SetupWizard
/system/product/priv-app/ims
/system/product/priv-app/SoundRecorder
/system/product/priv-app/SettingsIntelligence 
/system/product/priv-app/PersonalAssistant
/system/product/priv-app/MiuiScanner
/system/product/priv-app/MiuiGallery
/system/product/priv-app/MiuiExtraPhoto
/system/product/priv-app/MiuiAod
/system/product/priv-app/Mirror
/system/product/priv-app/MiMover
/system/product/priv-app/MiShare
/system/product/priv-app/MiService
/system/product/priv-app/MiBrowserGlobal
/system/product/priv-app/GoogleRestore
/system/product/priv-app/CleanMaster
/system/product/priv-app/AndroidAutoStub
/system/product/priv-app/Calendar
/system/product/priv-app/CarrierServices
/system/product/priv-app/MiuiScanner
/system/product/priv-app/Music
/system/vendor/app/SoterService
/system/product/priv-app/Weather
/system/product/app/MiSound
/system/product/app/FileExplorer
/system/product/app/MiuiFrequentPhrase
/system/system/app/CatchLog
/system/system_ext/priv-app/QualcommVoiceActivation
/data/app/android.autoinstalls.config.Xiaomi.begonia-qReVd01fGz2adoFNLXNDew==
/data/app/com.miui.analytics-JEa_Zu6x4mDKRv-IsGDPAA==
/system/data/app/~~NXSo0g7yTUEMlcaDN1TtVw==/com.google.android.projection.gearhead-CBQuMqaBbrvGaNILE1-1ig==
/system/data/app/~~zFmI0nYK4-3oAuDzvdOhKA==/com.google.android.as-3om-J49Vi54PfGvbE5bXYA==

/system/data/app/~~RzcAhge6nXQkIzh-T5Ya7g==/com.google.android.apps.turbo-vUZz2MO6TQu9ubVqlX55mw==
/system/data/app/~~olUb0x7xme6JMyDmYVV0rA==/com.google.android.apps.wellbeing-_v4uk9FdqmNAgTTDfIy2Gg==

/system/data/app/~~ErCy1FIEl-ah6E-XwQsieQ==/com.google.android.apps.nbu.files-z0KerP6vK7CUFdF36Fy1Rg==
/system/product/app/PhotoTable

/system/data/app/~~ULKGyy4A7mZo0Y6IORwUUA==/com.google.android.settings.intelligence-lR76t2CEkp2e9dIsS-t9Xg==
/system/data/app/~~QXwD_cx29GCwuX0kf_6oqQ==/com.google.android.videos-kg0GDdpVDPIX8e-zO3o6pQ==
/system/system/priv-app/LiveWallpapersPicker
/system/system/app/PrintSpooler
/vendor/data/app/Drive
/vendor/data/app/Duo
/vendor/data/app/GlobalFashiongallery
/vendor/data/app/Music2
/vendor/data/app/Photos
/vendor/data/app/Videos
/vendor/data/app/wps_lite
/vendor/data/app/XMRemoteController
"

on_install() {
  ui_print "   Extrayendo archivos del modulo...   "
  unzip -o "$ZIPFILE" 'system/*' -d $MODPATH >&2
}

set_permissions() {
  set_perm_recursive $MODPATH 0 0 0755 0644
}
